SimpleBlog/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.Entities.Dtos;
using SimpleBlog.Services.Constracts;

namespace SimpleBlog.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    [Route("[area]/[controller]/[action]")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var result = await _categoryService.GetCategory();
                return View((List<CategoryDto>)result);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return StatusCode(500);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Raw()
        {
            try
            {
                var result = await _categoryService.GetCategory();
                var data = new JsonResult((List<CategoryDto>)result);
                dynamic response = new
                {
                    Data = (List<CategoryDto>)result,
                    Draw = "1",
                    RecordsFiltered = ((List<CategoryDto>)result).Count,
                    RecordsTotal = ((List<CategoryDto>)result).Count
                };
                return Ok(response);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return StatusCode(500);
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromBody]CategoryDto category)
        {
            try
            {
                CategoryDto result = null;
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);
                else
                {
                    category.CreatedDate = DateTime.Now;
                    category.UpdatedDate = DateTime.Now;
                    result = await _categoryService.AddCategoryAsync(category);                 
                }
                return new JsonResult(result);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return BadRequest();
            }
        }

        public async Task<IActionResult> Update(int? Id)
        {
            if (Id == null) return NotFound();
            var category = await _categoryService.GetCategory(Id.Value);
            if (category == null) return NotFound();
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [FromBody]CategoryDto category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    category.UpdatedDate = DateTime.Now;
                    await _categoryService.UpdateCategory(category);
                    return new JsonResult(category);
                }
                return View(category);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return BadRequest();
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var category = await _categoryService.GetCategory(id.Value);
                if (category == null)
                {
                    return NotFound();
                }
                await _categoryService.DeleteCategory(category);
                return new JsonResult(new { result = "Success" });
            }
            catch (Exception e)
            {
                throw e;
            }
        }
    }
}

SimpleBlog/Areas/Admin/Controllers/FooterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SimpleBlog.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    [Route("[area]/[controller]/[action]")]
    public class FooterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SimpleBlog/Areas/Admin/Controllers/MainMenuController.cs
using SimpleBlog.Entities.Dtos;
using SimpleBlog.Services.Constracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SimpleBlog.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    [Route("[area]/[controller]/[action]")]
    public class MainMenuController : Controller
    {
        private readonly IMainMenuService _mainMenuService;
        public MainMenuController(IMainMenuService mainMenuService)
        {
            _mainMenuService = mainMenuService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var result = await _mainMenuService.GetMainMenu();
                return View((List<MainMenuDto>)result);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return StatusCode(500);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Raw()
        {
            try
            {
                var result = await _mainMenuService.GetMainMenu();
                var data = new JsonResult((List<MainMenuDto>)result);
                dynamic response = new
                {
                    Data = (List<MainMenuDto>)result,
                    Draw = "1",
                    RecordsFiltered = ((List<MainMenuDto>)result).Count,
                    RecordsTotal = ((List<MainMenuDto>)result).Count
                };
                return Ok(response);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return StatusCode(500);
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromBody]MainMenuDto mainMenu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    mainMenu.CreatedDate = DateTime.Now;
                    mainMenu.UpdatedDate = DateTime.Now;
                    await _mainMenuService.AddMainMenuAsync(mainMenu);
                    return new JsonResult(mainMenu);
                }
                return View(mainMenu);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return BadRequest();
            }

        }

        public async Task<IActionResult> Update(int? Id)
        {
            if (Id == null) return NotFound();
            var mainMenu = await _mainMenuService.GetMainMenu(Id.Value);
            if (mainMenu == null) return NotFound();
            return View(mainMenu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [FromBody]MainMenuDto mainMenu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    mainMenu.UpdatedDate = DateTime.Now;
                    await _mainMenuService.UpdateMainMenu(mainMenu);
                    return new JsonResult(mainMenu);
                }
                return View(mainMenu);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return BadRequest();
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var mainMenu = await _mainMenuService.GetMainMenu(id.Value);
                if (mainMenu == null)
                {
                    return NotFound();
                }
                await _mainMenuService.DeleteMainMenu(mainMenu);
                return new JsonResult(new { result = "Success" });
            }
            catch (Exception e)
            {
                throw e;
            }
        }

    }
}

SimpleBlog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using SimpleBlog.Entities;
using SimpleBlog.Entities.Dtos;
using SimpleBlog.Services.Constracts;
using SimpleBlog.Infastructure.Helpers;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace SimpleBlog.Controllers
{
    [Route("/bai-viet-moi-nhat")]
    public class PostController : Controller
    {
        private readonly IOptions<BlogSetting> config;
        private readonly IPostService _newService;
        public PostController(IPostService newsService, IOptions<BlogSetting> config)
        {
            _newService = newsService;
            this.config = config;
        }
        [HttpGet("")]
        public async Task<IActionResult> Index([FromQuery]int page = 0, int categoryId = 0)
        {
            int pageSize = config.Value.PageSize;
            PaginatedItems<PostDto> result = null;
            if (categoryId == 0)
                result = await _newService.GetPosts(page, pageSize);
            else
                result = await _newService.GetPostByCategoryId(categoryId, page, pageSize);
            ViewData["MaxPage"] = Math.Ceiling((double)result.Count / pageSize);
            ViewData["prev"] = result.PageIndex + 1;
            ViewData["next"] = page <= 1 ? 0 : page - 1;
            return View((List<PostDto>)result.Data);
        }
        [HttpGet("chi-tiet")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var news = await _newService.GetPostById(id.Value);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }
    }
}

SimpleBlog/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Trang quản trị</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap/dist/css/style.css" rel="stylesheet" />
    <!-- MetisMenu CSS -->
    <link href="~/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- DataTables CSS -->
    <link href="~/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
    @RenderSection("Head", required: false)
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/admin/home/index">Quản trị website</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">              
                <li class="dropdown">
                    @await Html.PartialAsync("_LoginPartial")
                </li>
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    @RenderSection("sidebar", required: false)
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div class="container">
            @RenderBody()
        </div>

        <!-- /#page-wrapper -->
    </div>

    <!-- jQuery -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- DataTables JavaScript -->
    <script src="~/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/dist/js/sb-admin-2.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SimpleBlog/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<ul class="nav" id="side-menu">
    <li class="sidebar-search">
        <div class="input-group custom-search-form">
            <input type="text" class="form-control" placeholder="Tìm kiếm...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                    <i class="fa fa-search"></i>
                </button>
            </span>
        </div>
        <!-- /input-group -->
    </li>
    <li>
        <a href="/admin/home/index"><i class="fa fa-dashboard fa-fw"></i> Bảng theo dõi</a>
    </li>
    <li>
        <a asp-area="Admin" asp-controller="MainMenu" asp-action="Index"><i class="fa fa-bar-chart-o fa-fw"></i>Quản lý menu</a>
        <!-- /.nav-second-level -->
    </li>
    <li>
        <a asp-area="Admin" asp-controller="Post" asp-action="Index"><i class="fa fa-table fa-fw"></i>Quản lý<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li>
                <a asp-area="Admin" asp-controller="Post" asp-action="Index">Bài viết</a>
            </li>
            <li>
                <a asp-area="Admin" asp-controller="Category" asp-action="Index">Chủ đề</a>
            </li>
        </ul>
    </li>
    <li>
        <a asp-area="Admin" asp-controller="CompanyInfo" asp-action="Index"><i class="fa fa-edit fa-fw"></i>Thông tin công ty</a>
    </li>
    <li>
        <a asp-area="Admin" asp-controller="Footer" asp-action="Index"><i class="fa fa-edit fa-fw"></i>Chỉnh sửa footer</a>
    </li>
</ul>